### ISSUE TITLE
日時指定の際に、再構築がエラーで止まってしまう事象に関して

### ISSUE THREAD

**Issue by kazu-aw** [movabletype/mt-plugin-fiscal-yearly-archives#1]
はじめましてkazuと申します。

こちら、素晴らしいプラグインの作成誠にありがとうございます。
https://plugins.movabletype.jp/author77abc/fiscalyearlyarchives.html
よりDLをさせていただいたのですが、こちらに関しまして、MT7 r.5402で使用していた所、
記事を日時指定公開にて公開を行った際に、Can't locate object method "blog" via package "MT" at /{PATH}/plugins/FiscalYearlyArchives/lib/FiscalYearlyArchives/Util.pm line 23.
とログ上に表示され、再構築がエラーで止まってしまう状況となっております。

通常の公開作業などは問題が無い事から、
おそらく、run-periodic-tasks経由で日付指定公開を行った場合は、
以下の「$app->blog」および、「$app->blog->id」がうまく取れないのだと思うのですが、
修正方法などご教示いただいたりすることは可能でしょうか？
https://github.com/movabletype/mt-plugin-fiscal-yearly-archives/blob/dc930de35c970b7794ddf4d0d2ec60a714c0f71d/plugins/FiscalYearlyArchives/lib/FiscalYearlyArchives/Util.pm#L23

お忙しい中、大変恐縮ではございますが、ご確認いただければ幸いでございます。
以上、ご多忙の折誠に恐縮ではございますが、何卒よろしくお願い申し上げます。

**Comment by hideki-a** [comment]
`start_end_fiscal_year`サブルーチンの呼び出し元を確認すると、たいてい第2引数で`MT::Blog`オブジェクトを渡しているようです。
※渡していない場合も呼び出しの前に`$blog = $ctx->stash('blog')`があるので、`$blog`を第2引数にすれば良さそうです。

そこで、`start_end_fiscal_year`サブルーチンの中で以下のようにすれば設定値が取得できるようでした。
```perl
sub start_end_fiscal_year {
    my $ts = shift;
    my $blog = shift;
（省略）
    my $config = $plugin->get_config_hash( 'blog:' . ( $blog ? $blog->id : 0 ) );
```

一応ローカルで試して動いたのですが、Perlは得意でないので違っていたらすみません。

**Comment by kazu-aw** [comment]
ありがとうございます。
こちら確認を行いました所、run-periodic-tasks経由で日付指定公開の記事が存在する際に、$blogも取れない場合があり、
$blog->idにて、Can't call method "id" on an undefined valueが表示されました。

残念ながら、解決には至っておりませんが、お時間を頂戴し、本当にありがとうございます。

以上、よろしくお願いいたします。

**Comment by taitetsu** [comment]
ご報告ありがとうございます。

本件につきまして、解決に向けて検討を進めております。

少しお時間をいただくことになるかもしれませんが、よろしくお願いいたします。

**Comment by kazu-aw** [comment]
ご返信、誠にありがとうございます。

MTの仕様の色が濃いように思われ、完全に困り果てておりました。
引き続き私の方でも解決に向け、何かわからないかを調べてまりますが、
ご多忙の中、誠に恐縮ではございますが、見ていただけますと幸いでございます。

以上、何卒よろしくお願い申し上げます。

**Comment by taitetsu** [comment]
バージョン 0.22 をリリースしました。

https://github.com/movabletype/mt-plugin-fiscal-yearly-archives/releases/tag/v0.22

本件ですが、調査したところ、サイト毎の開始月設定を指定日公開時に取得するためにはプラグイン側の対応だけでは足りず、MT 本体側の対応が必要であることが判明しました。
ということでバージョン 0.22 では、申し訳ございませんが、開始月の設定をシステムスコープへと移動させていただきました。
これまでのようにサイト毎に開始月を設定することはできず、システムとして一つだけ、開始月を指定することになります。

MT の次期バージョンにて MT 本体のコードに手を入れた上で、その新しい MT 対応バージョンとしてサイト毎の開始月設定を復活させる予定です。
よろしくお願いいたします。
