### ISSUE TITLE
MT8.04でのエラー

### ISSUE THREAD

**Issue by van-web** [movabletype/mt-plugin-fiscal-yearly-archives#3]
プラグインを使わせていただいています。ありがとうございます。
MT8.04にて再構築を行うと、「Can't locate object method "_get_preferred_map" via package "FiscalYearlyArchives::ContentTypeFiscalYearly"」が出るようになりました。
こちらのgithubを確認しましたら、0.22が出ておりましたので、更新しましたが、残念ながら同じエラーが出ました。
よろしければご確認いただけると幸いです。

**Comment by taitetsu** [comment]
@van-web お返事が遅くなり申し訳ございません。
MT7 より _get_preferred_map が get_preferred_map とリネームされ、互換性のために _get_preferred_map も残されていたのですが、MT8 にて _get_preferred_map が破棄されたことがエラーの原因となります。
近く、対策バージョンをリリースの予定です。

**Comment by van-web** [comment]
@taitetsu ご返答いただきありがとうございます。ぜひ、よろしくお願いいたします。

**Comment by taitetsu** [comment]
@van-web お世話になっております。
本 issue を修正したバージョン 0.23 をリリースしました。
https://github.com/movabletype/mt-plugin-fiscal-yearly-archives/releases/tag/v0.23
よろしくお願いいたします。

**Comment by van-web** [comment]
迅速にご対応いただき、ありがとうございました。大変助かります！重ねて、ありがとうございました。

**Comment by taitetsu** [comment]
解決、ということでクローズします。
