### ISSUE TITLE
言語設定について

### ISSUE THREAD

**Issue by Noriakky** [movabletype/mt-plugin-fiscal-yearly-archives#4]
プラグイン、使わせていただいています。まことにありがとうございます。
質問なのですが英語サイトに利用したいので「年度」というのを取りたいです。全般設定「使用言語」を英語にしても「年度」がついてくるのですが何か方法はありますでしょうか？
ご教示いただければありがたいです。

**Comment by taitetsu** [comment]
@Noriakky ご報告ありがとうございます。
英語の翻訳を用意しておりませんでした。
英語の翻訳を追加したバージョン 0.23 をリリースしました。
https://github.com/movabletype/mt-plugin-fiscal-yearly-archives/releases/tag/v0.23
よろしくお願いいたします。

**Comment by Noriakky** [comment]
ご連絡ありがとうございます。
「Fixed an issue with English translation in dynamic publishing.」とありますがダイナミックパブリッシングのみの対応でしょうか？
スタティックパブリッシングでも「年度」表記が無くなりますでしょうか？

**Comment by taitetsu** [comment]
@Noriakky https://github.com/movabletype/mt-plugin-fiscal-yearly-archives/commit/11baeb8ac03eb572fc41e39515831527198a107e にてスタティック時の翻訳も追加しております。

**Comment by Noriakky** [comment]
今実装してみたのですが<$mt:ArchiveTitle$>と記述してみると「年度」がついてきます。スタティックパブリッシングでブログの使用言語は使用言語はEnglishにしています。v.023ファイルはすべてサーバアップ済で
plugins/FiscalYearlyArchives/lib/FiscalYearlyArchives/L10N/en_us.pm
もサーバにいます。
何かほかに設定が必要でしょうか？あれこれと聞いて申し訳ありません。
ご教示いただけましたら有難いでです。

**Comment by taitetsu** [comment]
@Noriakky すみません、対応が不完全だったようです。追加で修正を入れます。

**Comment by Noriakky** [comment]
よろしくお願いいたします。

**Comment by taitetsu** [comment]
@Noriakky お待たせして申し訳ございません。
諸々対応したバージョン 0.24 をリリースしました。
https://github.com/movabletype/mt-plugin-fiscal-yearly-archives/releases/tag/v0.24
MT7、MT8 それぞれの最新バージョン（8.4.0 と r.5505。8.0.4 は対象外）以降に対応しています。
よろしくお願いいたします。

**Comment by Noriakky** [comment]
@taitetsu 
ご連絡ありがとうございます。
差し替えました。英語版は「FY」とつくのですね。ご対応・ご教示ありがとうございます。

**Comment by taitetsu** [comment]
@Noriakky ありがとうございます。
こちら解決したということで閉じます。
